### ISSUE TITLE
v3.0.0 missing from Terraform Registry

### ISSUE THREAD

**Issue by jacobwoffenden** [terraform-aws-modules/terraform-aws-managed-service-prometheus#17]
## Description

Same as https://github.com/terraform-aws-modules/terraform-aws-managed-service-prometheus/issues/14 but for v3.0.0

[v3.0.0](https://github.com/terraform-aws-modules/terraform-aws-managed-service-prometheus/releases/tag/v3.0.0) is the latest release on GitHub 
[v2.2.3](https://registry.terraform.io/modules/terraform-aws-modules/managed-service-prometheus/aws/2.2.3) is the latest release on the registry

**Comment by antonbabenko** [comment]
Fixed.
