### ISSUE TITLE
Complete example does not work

### ISSUE THREAD

**Issue by schniber** [terraform-aws-modules/terraform-aws-managed-service-prometheus#7]
## Description

The complete example does not work.
if you clone the repository and run the complete example you end up with the following error:
```
╷
│ Error: Invalid index
│ 
│   on ../../main.tf line 2, in locals:
│    2:   workspace_id = var.create_workspace ? aws_prometheus_workspace.this[0].id : var.workspace_id
│     ├────────────────
│     │ aws_prometheus_workspace.this is empty tuple
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
```

If your request is for a new feature, please use the `Feature request` template.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: v2.2.0

- Terraform version: v1.3.3

- Provider version(s): v4.35.0

## Reproduction Code [Required]

 No
 Yes

1/ Clone the repository
2/ cd into examples/complete
3/ run terraform init
4/ run terraform plan

## Expected behavior

Terraform plan should go through.

## Actual behavior
terraform plan fails as it's unable to identify the dependencies : 
```
╷
│ Error: Invalid index
│ 
│   on ../../main.tf line 2, in locals:
│    2:   workspace_id = var.create_workspace ? aws_prometheus_workspace.this[0].id : var.workspace_id
│     ├────────────────
│     │ aws_prometheus_workspace.this is empty tuple
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
```

**Comment by bryantbiggs** [comment]
closed in #9
