### ISSUE TITLE
Addition of Cloudwatch logging configuration for the Prometheus Workspace

### ISSUE THREAD

**Issue by schniber** [terraform-aws-modules/terraform-aws-managed-service-prometheus#8]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is available in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

It would be great to be able to add the cloudwatch log group configuration to the prometheus workspace.

## Describe the solution you'd like.

Assign the logging_configuration attribute

```
logging_configuration {
    log_group_arn = "${aws_cloudwatch_log_group.example.arn}:*"
  }
```

**Comment by bryantbiggs** [comment]
closed in #9
